### PR TITLE
Using postStartCommand instead of postCreateCommand

### PR DESCRIPTION
**Pull request by jaredlander**
Since we want radian to launch every time the container is run, not just after creation, use postStartCommand instead of postCreateCommand.

### CODE REVIEW

**Comment by RamiKrispin** [comment]
Thanks!

**Comment by jaredlander** [comment]
I've been playing around and depending on the size of the image there can be problems with this command not finding the .R files the R extension adds to the workspace. I find that these modifications work, though I haven't made a PR for it yet.

```
"postStartCommand": "until [ -f /root/.vscode-R/init.R ]; do sleep 0.1; done; radian",                                                  "containerEnv": {
  "R_PROFILE_USER": "/root/.Rprofile",
  "TERM_PROGRAM": "vscode",
  "VSCODE_INIT_R": "R/session/init.R"
},
```

**Comment by RamiKrispin** [comment]
Thanks! Tested on the temlate, this fix the issue with the [plot viewer](https://github.com/REditorSupport/vscode-R/wiki/Plot-viewer). I will try to add those environment variable to the base image.

**Comment by RamiKrispin** [comment]
I updated the [Dockerfile](https://github.com/RamiKrispin/vscode-r-template/blob/ce07cc86d036600fadbc97743aa6186428517099/docker/Dockerfile.base-r#L26) on the GitHub template, works smoothly so far. I will update the tutorial in the coming weeks. Thanks!

**Pull request merged**
